#! /usr/bin/env python
# encoding: utf-8

top = '.'
out = 'build'

def options(ctx):
    pass

def configure(ctx):
    pass

def build(bld):
    for node in bld.path.ant_glob('**/*.py'):
        bld(rule='cp ${SRC} ${TGT}', source=node, target=node.get_bld())
