#! /usr/bin/env python
# encoding: utf-8

import os

top = '.'
out = 'build'

def options(ctx):
    ctx.load('google_closure')

def configure(ctx):
    ctx.load('google_closure')

def build(bld):
    bld.load('google_closure')

    src_roots = [bld.path.find_dir(p) for p in [
            'src',
            'lib/closure-templates',
            'lib/relief/relief',
        ]]

    bld_roots = set()

    for root in src_roots:
        b_root = root.get_bld()
        b_root.mkdir()
        bld_roots.add(b_root)

    roots = set(src_roots)
    roots.update(bld_roots)

    ## Closure Linter -- Detect style issues in the Javascript
    #bld(features='gjslint', roots=roots)

    ## Closure Stylesheets
    source = bld.path.ant_glob([os.path.join(root.path_from(bld.path), '**/*.gss') for root in roots])
    bld(source=source)

    ## Closure Templates
    source = bld.path.ant_glob([os.path.join(root.path_from(bld.path), '**/*.soy') for root in roots])
    bld(source=source)

    ## Closure Compiler
    bld.closure_compiler(
            roots      = [r.abspath() for r in roots],
            namespaces = ['__bootstrap'],
            target     = bld.path.find_or_declare('www/js/application.js'),
            compiler_flags = ['--compilation_level=ADVANCED_OPTIMIZATIONS'],
        )

    # Copy the www directory
    for node in bld.path.ant_glob('www/**/*'):
        bld(rule='cp ${SRC} ${TGT}', source=node, target=node.get_bld())

