// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../relief/relief/auth/auth_change_event.js', ['relief.auth.AuthChangeEvent', 'relief.auth.EventType'], ['goog.events']);
goog.addDependency('../../../relief/relief/auth/auth_manager.js', ['relief.auth.AuthManager'], ['goog.events.EventTarget']);
goog.addDependency('../../../relief/relief/auth/public_auth_manager.js', ['relief.auth.PublicAuthManager'], ['relief.auth.AuthManager', 'relief.auth.PublicUser']);
goog.addDependency('../../../relief/relief/auth/public_user.js', ['relief.auth.PublicUser'], ['relief.auth.User']);
goog.addDependency('../../../relief/relief/auth/simple_user.js', ['relief.auth.SimpleUser'], ['relief.auth.User']);
goog.addDependency('../../../relief/relief/auth/user.js', ['relief.auth.User'], []);
goog.addDependency('../../../relief/relief/cache/cache.js', ['relief.cache.Cache'], ['goog.math', 'goog.object', 'goog.string', 'goog.structs.LinkedMap', 'goog.structs.Map', 'relief.cache.Cloneable', 'relief.cache.SimpleValue']);
goog.addDependency('../../../relief/relief/cache/cloneable.js', ['relief.cache.Cloneable'], []);
goog.addDependency('../../../relief/relief/cache/simplevalue.js', ['relief.cache.SimpleValue'], []);
goog.addDependency('../../../relief/relief/commands/get_command.js', ['relief.commands.GetCommand', 'relief.commands.GetCommand.ResponseType'], ['goog.dom.xml', 'goog.json', 'relief.cache.Cloneable', 'relief.rpc.Command']);
goog.addDependency('../../../relief/relief/dates/tz.js', ['relief.dates.tz', 'relief.dates.tz.olson'], []);
goog.addDependency('../../../relief/relief/handlers/common_serviceprovider.js', ['relief.handlers.CommonServiceProvider'], ['relief.nav.NavServiceProvider']);
goog.addDependency('../../../relief/relief/handlers/error_configs.js', ['relief.handlers.errors'], ['relief.handlers.MessageHandler', 'relief.handlers.templates']);
goog.addDependency('../../../relief/relief/handlers/message_handler.js', ['relief.handlers.MessageHandler'], ['relief.nav.Handler']);
goog.addDependency('../../../relief/relief/handlers/redirect_handler.js', ['relief.handlers.RedirectHandler'], ['relief.nav.Handler', 'relief.utils']);
goog.addDependency('../../../relief/relief/handlers/static_handler.js', ['relief.handlers.StaticHandler'], ['goog.json', 'relief.commands.GetCommand', 'relief.commands.GetCommand.ResponseType', 'relief.handlers.templates', 'relief.nav.Handler']);
goog.addDependency('../../../relief/relief/nav/handler.js', ['relief.nav.Handler'], ['goog.disposable.IDisposable', 'relief.nav.NavServiceProvider', 'relief.nav.Path']);
goog.addDependency('../../../relief/relief/nav/nav_event.js', ['relief.nav.EventType', 'relief.nav.NavEvent'], ['goog.events.Event']);
goog.addDependency('../../../relief/relief/nav/nav_manager.js', ['relief.nav.NavManager'], ['goog.History', 'goog.events.EventHandler', 'goog.events.EventTarget', 'goog.history.EventType', 'relief.auth.EventType', 'relief.nav.NavEvent', 'relief.nav.NavServiceProvider', 'relief.nav.Path', 'relief.nav.URLMap', 'relief.utils']);
goog.addDependency('../../../relief/relief/nav/nav_serviceprovider.js', ['relief.nav.NavServiceProvider'], ['relief.ServiceProvider', 'relief.nav.URLMap']);
goog.addDependency('../../../relief/relief/nav/path.js', ['relief.nav.Path'], ['relief.nav.PageConfig']);
goog.addDependency('../../../relief/relief/nav/urls.js', ['relief.nav.PageConfig', 'relief.nav.URLMap'], []);
goog.addDependency('../../../relief/relief/rpc/command.js', ['relief.rpc.Command'], ['goog.Disposable']);
goog.addDependency('../../../relief/relief/rpc/rpc.js', ['relief.rpc.RPCService'], ['goog.Disposable', 'goog.json', 'goog.net.XhrManager', 'goog.structs.Map', 'relief.rpc.Command']);
goog.addDependency('../../../relief/relief/serviceprovider.js', ['relief.ServiceProvider'], ['goog.Disposable', 'goog.dispose']);
goog.addDependency('../../../relief/relief/testing/stubs.js', ['relief.testing.stubFn'], []);
goog.addDependency('../../../relief/relief/utils/utils.js', ['relief.utils'], ['goog.array', 'goog.dom']);
